name: Build and test

on:
  workflow_dispatch:

jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: |
            yarn.lock
            client/pwa/yarn.lock
            libs/**/*.js

      - name: Install root packages
        run: yarn --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install PWA
        working-directory: client/pwa
        run: yarn --frozen-lockfile

      - name: Store artifacts for later
        uses: actions/upload-artifact@v3
        with:
          name: build
          # Upload everything for now
          path: .

  lint:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download from build job
        uses: actions/download-artifact@v3

      - name: Run Prettier
        run: yarn prettier-check

      - name: Run ESLint
        run: yarn eslint

      - name: Run Stylelint
        run: yarn stylelint

      - name: Check TypeScript
        run: yarn check:tsc

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download from build job
        uses: actions/download-artifact@v3

      - name: Client unit tests
        run: yarn test:client

      - name: Libs unit tests
        run: yarn test:libs

      - name: Build and start server
        id: server
        env:
          ENV_FILE: .env.testing
        run: |
          yarn build:prepare
          yarn build

          yarn start:static-server > /tmp/stdout.log 2> /tmp/stderr.log &
          sleep 1
          curl --fail --retry-connrefused --retry 5 http://localhost:5042 > /dev/null

      - name: Functional tests
        run: |
          yarn test:testing
          yarn test:headless

      - name: Test m2h
        env:
          ENV_FILE: .env.testing
        run: |
          yarn m2h markdown/tool/m2h --locale en-US
          diff -s testing/content/files/en-us/markdown/tool/m2h/index.html testing/content/files/en-us/markdown/tool/m2h/expected.html

      - name: If bad things happened, show logs
        if: failure() && steps.server.outcome != 'skipped'
        run: |
          echo "STDOUT..................................................."
          cat /tmp/stdout.log
          echo ""
          echo "STDERR..................................................."
          cat /tmp/stderr.log
